data:
    mysql:
        debug: true
        dsn: root:6cd9aa521e1636b02dd1edd5e3ed22c8@tcp(43.142.16.102:33060)/gin-plus-admin?charset=utf8mb4&parseTime=True&loc=Local
info:
    title: github.com/aide-cloud/gin-plus
    version: v0.3.1
openapi: 3.0.3
paths:
    /api/role/create:
        post:
            operationId: Create
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/delete/:id:
        delete:
            operationId: Delete
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/detail/:id:
        get:
            operationId: Detail
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/edit/:id:
        put:
            operationId: Edit
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/list:
        get:
            operationId: List
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/status/:id:
        put:
            operationId: UpdateStatus
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/create:
        post:
            operationId: Create
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                avatar:
                                    type: string
                                    title: Avatar
                                birthday:
                                    type: integer
                                    title: Birthday
                                name:
                                    type: string
                                    title: Name
                                password:
                                    type: string
                                    title: Password
    /api/user/delete/:id:
        delete:
            operationId: Delete
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/detail/:id:
        get:
            operationId: GetDetail
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    created_at:
                                        type: integer
                                        title: CreatedAt
                                    files:
                                        type: array
                                        title: Files
                                        items:
                                            properties:
                                                ext:
                                                    type: string
                                                    title: Ext
                                                file_type:
                                                    type: object
                                                    title: FileType
                                                name:
                                                    type: string
                                                    title: Name
                                                size:
                                                    type: integer
                                                    title: Size
                                                url:
                                                    type: string
                                                    title: Url
                                                user_id:
                                                    type: integer
                                                    title: UserID
                                            type: object
                                    id:
                                        type: integer
                                        title: ID
                                    name:
                                        type: string
                                        title: Name
                                    update_at:
                                        type: integer
                                        title: UpdateAt
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/edit/:id:
        post:
            operationId: PostEdit
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/list:
        get:
            operationId: List
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/status/:id:
        put:
            operationId: UpdateStatus
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
server:
    http:
        host: 0.0.0.0
        port: 8080
    matadata:
        description: gin-plus-admin-app
        time: "2023-09-25 15:00:00"
    mode: debug
    name: gin-plus-admin-app
