info:
    title: github.com/aide-cloud/gin-plus
    version: v0.3.1
openapi: 3.0.3
paths:
    /api/auth/login:
        post:
            operationId: Login
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/auth/logout:
        post:
            operationId: Logout
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/auth/register:
        post:
            operationId: Register
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/create:
        post:
            operationId: Create
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/delete/:id:
        delete:
            operationId: Delete
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/detail/:id:
        get:
            operationId: Detail
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/edit/:id:
        put:
            operationId: Edit
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/list:
        get:
            operationId: List
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/role/status/:id:
        put:
            operationId: UpdateStatus
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/create:
        post:
            operationId: Create
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                avatar:
                                    type: string
                                    title: Avatar
                                birthday:
                                    type: integer
                                    title: Birthday
                                name:
                                    type: string
                                    title: Name
                                password:
                                    type: string
                                    title: Password
    /api/user/delete/:id:
        delete:
            operationId: Delete
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/detail/:id:
        get:
            operationId: GetDetail
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    created_at:
                                        type: integer
                                        title: CreatedAt
                                    files:
                                        type: array
                                        title: Files
                                        items:
                                            properties:
                                                ext:
                                                    type: string
                                                    title: Ext
                                                file_type:
                                                    type: object
                                                    title: FileType
                                                name:
                                                    type: string
                                                    title: Name
                                                size:
                                                    type: integer
                                                    title: Size
                                                url:
                                                    type: string
                                                    title: Url
                                                user_id:
                                                    type: integer
                                                    title: UserID
                                            type: object
                                    id:
                                        type: integer
                                        title: ID
                                    name:
                                        type: string
                                        title: Name
                                    update_at:
                                        type: integer
                                        title: UpdateAt
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/edit/:id:
        post:
            operationId: PostEdit
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                avatar:
                                    type: string
                                    title: Avatar
                                birthday:
                                    type: integer
                                    title: Birthday
                                name:
                                    type: string
                                    title: Name
    /api/user/list:
        get:
            operationId: List
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    list:
                                        type: array
                                        title: List
                                        items:
                                            properties:
                                                avatar:
                                                    type: string
                                                    title: Avatar
                                                birthday:
                                                    type: integer
                                                    title: Birthday
                                                files:
                                                    type: array
                                                    title: Files
                                                    items:
                                                        properties:
                                                            ext:
                                                                type: string
                                                                title: Ext
                                                            file_type:
                                                                type: object
                                                                title: FileType
                                                            name:
                                                                type: string
                                                                title: Name
                                                            size:
                                                                type: integer
                                                                title: Size
                                                            url:
                                                                type: string
                                                                title: Url
                                                            user_id:
                                                                type: integer
                                                                title: UserID
                                                        type: object
                                                name:
                                                    type: string
                                                    title: Name
                                                status:
                                                    type: object
                                                    title: Status
                                            type: object
                                    page_info:
                                        type: object
                                        title: PageInfo
                                        properties:
                                            curr:
                                                type: integer
                                                title: Curr
                                            size:
                                                type: integer
                                                title: Size
                                            total:
                                                type: integer
                                                title: Total
            parameters:
                - name: keyword
                  in: query
                  schema:
                    type: string
                    title: Keyword
                - name: curr
                  in: query
                  schema:
                    type: integer
                    title: Curr
                - name: size
                  in: query
                  schema:
                    type: integer
                    title: Size
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
    /api/user/password/:id:
        put:
            operationId: UpdatePassword
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                new_password:
                                    type: string
                                    title: NewPassword
                                old_password:
                                    type: string
                                    title: OldPassword
    /api/user/status/:id:
        put:
            operationId: UpdateStatus
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: ID
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                status:
                                    type: object
                                    title: Status
