server:
  name: gin-plus-admin
  mode: release
  matadata:
    version: 1.0.0
    description: gin-plus-admin
  http:
    host: "0.0.0.0"
    port: 8080
  
data:
  mysql:
    dsn: root:12345678@tcp(localhost:3306)/prom?charset=utf8mb4&parseTime=True&loc=Local
    debug: true